# Start the testnet server with the command 'docker-compose up -d'

version: "3.6"
services:
  koa-mongodb:
    image: mongo
    container_name: mongo-koa
    ports:
      - "5555:27017" # <host port>:<container port>
    volumes:
      - ./database:/data/db
    command: mongod --logpath=/dev/null # -- quiet
    restart: always

  faucet-backend:
    image: "node:10"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - FAUCET_ENV=production
      - BCHJSTOKEN= # Complete with your token
    volumes:
      - ./:/home/node/app
    command: "npm start"
    restart: always

  faucet-frontend:
    image: nginx
    volumes:
      - ./front-end:/usr/share/nginx/html:ro
    restart: always

  reverse-proxy:
    image: nginx
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./production/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
      - "7654:7654"
    restart: always
